### ISSUE TITLE
Several Bugfixes for Routerconfigs

### ISSUE THREAD

**Issue by Fireball2k15** [Cacti/plugin_routerconfigs#26]
Hi,

sorry for posting her, but I don't know how to upload my modiefied files to the project.
I worked for about three weeks to get the plugin running on my system and now I whant to share the bugfixes and improvements I made.
But how?

Fireball

**Comment by netniV** [comment]
See the link I posted on #25 as it gives a small guidance on how to do things. Just change `cacti/cacti` with `cacti/plugin_routerconfig` and any solo `cacti` with `routerconfig`

**Comment by netniV** [comment]
Alternatively, zip up the sources files and attach them to this issue and I will sort out getting them to here as a pull request..

**Comment by Fireball2k15** [comment]
Thanks for your help. I attach the Files here.
There is one special think I found out that you have to consider when you install routerconfigs:
In the File "cacti/include/global.php" you have to appent the Array in Line 102 with the following value  'router-redownload.php' .
Otherwise the scheduled download will not work.

Fireball
[routerconfigs.zip](https://github.com/Cacti/plugin_routerconfigs/files/1670909/routerconfigs.zip)

**Comment by netniV** [comment]
I haven’t started to look at the download yet as my machine is running through OS updates. 

However, you should t need to modify the base code to achieve what you wanted. That array is just for base files and you should be setting $no_http_headers to true before the first include if you don’t want headers.

**Comment by Fireball2k15** [comment]
ok, I changed this in the plugin and will check.
But this will take a while until it is triggered.

**Comment by netniV** [comment]
The zip file you uploaded seems to be missing a lot of files.  Are you sure it's correct?

**Comment by netniV** [comment]
Moreover, when I took the contents that were in the zip file, nothing was different to the github version.

**Comment by cigamit** [comment]
A pull request would be the best way to go Mr/s. Fireball

**Comment by Fireball2k15** [comment]
I modiefyed the following Files:
functions.php
router-accounts.php
router-backups.php
router-compare.php
router-devices.php
router-devtypes.php
setup.php

I can although place diff Files if you want to.

**Comment by Fireball2k15** [comment]
I checked the change of "$no_http_headers"in the router-redownload - it works fine.

**Comment by netniV** [comment]
None of those files where in the .zip that I could see.

**Comment by Fireball2k15** [comment]
ok, i try again
[routerconfigs.zip](https://github.com/Cacti/plugin_routerconfigs/files/1672780/routerconfigs.zip)

**Comment by netniV** [comment]
OK, I have these changes now. I'm going to provide this a commit and then comment on my observations.  @cigamit may have some further observations before he applies the commit too.

**Comment by netniV** [comment]
See https://github.com/netniV/plugin_routerconfigs/compare/Issue-26

Note, I didn't pull in the Text/* folder as @cigamit has updated that in a recent pull. I'm assuming now changes where made to those files since they weren't listed above.  However, I haven't tested if your code works with the updated Text/* folder.

**Comment by netniV** [comment]
Here are my notes so far.  There's quite a bit here so take some time to read it and let me know your thoughts as I could be (mis)reading some parts in a way you understand better 👍 

# Code Format
## variable comparison
You seem to use the value first followed by the check.  I know that in some languages, like C#, this is always prefered in case you are checking against a null value, but in most cacti code, it follows the normal format, ie, 
- Incorrect:
   `2 > strlen($info['ftpserver'])`
- Correct:
   `strlen($info['ftpserver']) > 2'`

## Bracket format
The cacti code has a defined format where brackets appear on the same like as the code.  This took me a few goes to get used to as in Visual Studio and C#, they are normally on the next line using the defaults.

- Incorrect:
   ```
   if (true)
   {
         true-stuff
   } 
   else
         else-stuff
   ```
- Correct:
   ```
   if (true) {
         true-stuff
   } else {
         else-stuff
   }
   ```

## Code alignment
Code should use TABS for indentation and spaces only for the last part of alignment where required. SQL statements are formatted as follows:

```
$db_setting = db_fetch_row_prepared('SELECT value
        FROM settings_user
        WHERE name = ?
        AND user_id = ?',
        array($config_name, $effective_uid));
```
# Code changes   
### functions.php 
   - **plugin_routerconfigs_download_config()**     
      - Seems to be bypassing the %SERVER% and %FILE% options which could be used
      - Debug log shows 'copy tftp result' which should probably be changed to 'command result'
      - Altering the CONFIRM portion to not send a 'y' which could break TFTP-based connections      
     - Repeating the DoCommand('') for some reason, any particular reason for 3 of them? 
         If so, should that be a configurable amount?
   - **plugin_routerconfigs_retrieve_account()**
      - No need for true== on the isset
      - No need for isset checks on password/enablepw since these are part of the table.  If username is set, these fields will be present even if they hold a null value.
      - Expanded the SQL statement from all fields to specific ones.  Was there an error there for some reason?
   - **plugin_routerconfigs_log()**
      - Changed the date logging format to reverse date.  Should probably change this again to use cacti's date formatting so that it creates consistent logs for the admin
      - Changed the default logging level to 5 which is super verbose debugging
      - Furthermore, I think this should just use cacti's cacti_log() function rather than having its own since it's replicating the same functionality without any of the fixes eg:
         ```
         function plugin_routerconfigs_log($string) {
         	$log_level = POLLER_VERBOSITY_LOW;
         
         	// Check for ERROR: in case there is any of the others too
         	if (substr_count($string,'ERROR:') || substr_count($string,'STATS:')) {
         		$log_level = POLLER_VERBOSITY_LOW;
         	} else if (substr_count($string,'WARNING:')) {
         		$log_level = POLLER_VERBOSITY_MEDIUM;
         	} else if (substr_count($string,'NOTICE:')) {
         		$log_level = POLLER_VERBOSITY_HIGH;
         	} 
         	cacti_log($string,false,'ROUTERCONFIGS', $log_level);
         ```

   - **PHPSsh->Connect()**
         - Added [name] to $devicetype in the first echo, but the array key should be in quotes, `$devicetype['name']`
         - Added $sleeptime but don't appear to use it
   - **PHPTelnet->__construct()**
      - Changed to be a function PHPTelnet() for some reason?
   - **PHPTelnet->Connect()**
      - Changed the default return value to be 9, which is the same as timing out receiving a password
         ```
         if ($x == 10) {
            return 9;
        }
        ```
      - Added code to check for automatic `enable` but this should probably be done more like below without resetting the $rv):
        ```
        $res .= $r;
        if (strpos($r, '#') !== FALSE) {
                $enablepw = '';
                break;
        } else if (strpos($r, '>') !== FALSE) {
                break;
        }
        $x++;
        ```
### router-accounts.php
   - no real issues here except maybe keep the $save assignments together

### router-backups.php
  - no issues

### router-compare
   - Now pulls back all devices even if they aren't needed (ie, we already have two devices to compare)
   - Your `0!=$file` code would potentially not set $device1 or $device2, which is OK, but then by you changed the `||` comparision to and `&&` which means that should a config not be found on one side or the other, no config is displayed at all.
      ```
      	if(0!=$file1)
      		$device1 = db_fetch_row_prepared('SELECT id,directory,filename,config FROM plugin_routerconfigs_backups WHERE id = ?', array($file1));
      	if(0!=$file2)
      		$device2 = db_fetch_row_prepared('SELECT id,directory,filename,config FROM plugin_routerconfigs_backups WHERE id = ?', array($file2));

      	if (isset($device1['config']) && isset($device2['config'])) {
      ```
   - The same is true for the count of lines. Should both be empty then display the warning, but you should allow one config to be displayed if it is there.

### router-devices.php
   - You added `<pre>` tags but then commented them out.  If they aren't needed, these should be removed from the code

### router-redownload.php
   - You have had to add the $no_http_headers value because you've included the global.php from cacti.  Was there a reason for including this? I'm thinking this relates to the read_config_option() calls you've added?

### setup.php
   - FTP Server column is quite short at 20 characters if using an FQDN.
   - You have left a lot of debug logs in the code but commented them out.  These would be better either removed or adding the POLLER_VERBOSITY _DEBUG option to the fourth parameter so that they are only recorded when really wanted (such as someone placing the plugin into the debug plugins list).
   - Added a below 60 check for the poller timer.  Not sure if that is correct without checking the poller code.

**Comment by Axel577** [comment]
@Fireball2k15 Wow! The first time I downloaded a routerconfigs version which is working from the beginning without having to do any changes manually. Like it!!

PS: and the scheduled backups work, too. Awesome!

**Comment by Fireball2k15** [comment]
Hi netniV,
thanks for reading my code that carefully. I've soe comments for expanation:
## functions.php
### plugin_routerconfigs_download_config()

- Repeating the DoCommand('') for some reason, any particular reason for 3 of them?
If so, should that be a configurable amount?
-> This is because I need several confirms to start the copy – three times will be ok (user, password, filename)

### plugin_routerconfigs_retrieve_account()
- Expanded the SQL statement from all fields to specific ones. Was there an error there for some reason?
-> I did this because in the both tables are fields with the same name – this was one of the major bugs – took me about two days to figure it out.

### plugin_routerconfigs_log()
-> I agree with you about the use of the cacti-Log function. I just tried to make it work

### PHPSsh->Connect()
-> If the sleeptime is missing, you get an error about using an non existing variable. I think this is about the use of global variables, or so.

### PHPTelnet->Connect()
-> I insert this part of code, because the ‘#’ character wasn’t found properly, so as a result of this the loop runs until the counter exceeds.

## router-compare
-> You are right, there is surely a better way to do this. I had the problem that wenn I try to compare two files, the first was chosen, and afterwards the routerconfigs plugin gets disabeld.

## router-redownload.php
-> The global was already included, I added the $no_http_headers after the tip of you

## setup.php
- Added a below 60 check for the poller timer. Not sure if that is correct without checking the poller code.
-> If I didn’t insert this check the redownload is never triggered.

Thanks again for your assistence - I'm not that programmer, for sure. And I would appreciate it if someone to impove my "quick fixes".

Fireball

**Comment by netniV** [comment]
- plugin_routerconfigs_download_config()
  We will need to revisit this I think because the number of DoCommand('') is specific to the device and command you are attempting to use (what is yours btw?).

- plugin_routerconfigs_retrieve_account()
  The SQL change could have some effects elsewhere but since it is working for you and @Axel577 we should be OK.

- plugin_routerconfigs_log()
  I'll make some changes in the branch I've made to do this.  This isn't your problem, it's just something I noticed when I reviewed the code.

- PHPSsh->Connect()
So this is a bug that hasn't been raised yet.  When I investigated $sleeptime, nothing else was showing up.  I forgot to check for class-based access and found the sleep function which uses it, so that's a good find:
   ```
   function Sleep() {
       if ($this->use_usleep) usleep($this->sleeptime);
       else sleep(1);
   }
   ```

- PHPTelnet->Connect()
  Yeah that was a good call on the `#` symbol.  I just think the code should be reworked slightly.  I'm still curious about the $rv=9 part?

- setup.php
   I think your code is probably right, I'm just not 100% about that area of things.  The chances are if left long enough it may have triggered, but if you have your polling time quite high and then multiple by 60... that could be quite a wait ;-)

If I have a device similar to yours, I may be able to even set this up and test it.  I think the biggest part of this @cigamit  would have issue with is around the parts that can break TFTP or assume a specific number of returns are needed on every device.  Maybe we should add a "ReturnConfirms" column to allow configuration of just how many to send.

**Comment by netniV** [comment]
What I might do is to pull out the few bug fixes, since we know those can be applied without breaking other code, and then look more at the FTP functionality.

**Comment by netniV** [comment]
I have now modified the plugin_routerconfigs_log() function on the above branch.

**Comment by Fireball2k15** [comment]
Hi netniV,
I use several Cisco devices as Routers, Switches and ASAs.
Yes I'm sure there is a better way else to set $rv=9. The thougth behind was that if I can find the '#' or use enable successful everything is ok - otherwise there went something wrong...

**Comment by netniV** [comment]
So you were trying to inverse the logic so that it assumes failure unless it succeeds.

**Comment by Fireball2k15** [comment]
Yes, in this condition it seams good to me to fix the problems without rewriting the complet function.

**Comment by netniV** [comment]
OK, I have my own separate scripts for backing those up but I can probably test this along side them.

**Comment by cigamit** [comment]
How long till we see a pull request?

**Comment by netniV** [comment]
See above, there is already an existing one.  I just think there are a few things that should be looked over.

**Comment by rcsmota** [comment]
@Fireball2k15 After a long time it's working. In the "old Cacti" was working but after change to Cacti 1.x its the first time.
Thanks a lot @Fireball2k15

**Comment by netniV** [comment]
@rcsmota I have just updated this plugin to a new version via a pull request.  Are you using my new version or the one above from @Fireball2k15 ?  

If it isn't mine, would you mind trying out the latest develop code ?  There are a great many changes I made as a company I was working with were trying to use this plugin and it was failing miserably so I went into its guts and ripped half the duplicated code out, made it more cacti.log friendly and more importantly work with more devices than previously 

Some of the big changes include:
- Handling the automatic enable (as per @Fireball2k15 )
- Masking passwords from the debug logs given out by PHPTelnet/PHPSsh etc
- Find success state with more devices by reducing check from "successfully" to "successful"
- Removing router-redownload and making router-download call a single function no matter what type of download it was trying to do
- Allow specifying a comman separated device list to router-download so you can test one or more devices
- Fix issue where router-download.php wouldn't even run because it was mixed up about what directory it was in

**Comment by cigamit** [comment]
Great teamwork guys.  I was hoping someone would come along and get the kinks worked out of this one.

**Comment by rcsmota** [comment]
@netniV I was using the @Fireball2k15 version. Now I tried with the new version and have some issues.

This is my  cacti log output. 

018/02/20  14:12:22 - DBCALL ERROR: SQL Save Failed for Table  'plugin_routerconfigs_devices'.  SQL:'INSERT INTO  plugin_routerconfigs_devices (`id`, `enabled`, `hostname`, `ipaddress`,  `directory`, `account`, `devicetype`, `schedule`, `connect_type`) VALUES  (0, 'on', 'SW_CORE_01', '192.168.120.2', 'switches', 1, 1, 7, 'both')  ON DUPLICATE KEY UPDATE `enabled`=VALUES(`enabled`),  `hostname`=VALUES(`hostname`), `ipaddress`=VALUES(`ipaddress`),  `directory`=VALUES(`directory`), `account`=VALUES(`account`),  `devicetype`=VALUES(`devicetype`), `schedule`=VALUES(`schedule`),  `connect_type`=VALUES(`connect_type`)'
--
2018/02/20 14:12:22 - CMDPHP SQL Backtrace:  (/plugins/routerconfigs/router-devices.php: 151  save_devices)(/plugins/routerconfigs/router-devices.php: 415  sql_save)(/lib/database.php: 1001 _db_replace)(/lib/database.php: 948  db_execute)(/lib/database.php: 135  db_execute_prepared)(/lib/database.php: 208 cacti_debug_backtrace)
2018/02/20 14:12:22 - CMDPHP ERROR: A DB Exec Failed!, Error: Unknown column 'connect_type' in 'field list'
2018/02/20 14:12:22 - DBCALL ERROR: A DB Exec Failed!, Error:1054,  SQL:'INSERT INTO plugin_routerconfigs_devices (`id`, `enabled`,  `hostname`, `ipaddress`, `directory`, `account`, `devicetype`,  `schedule`, `connect_type`) VALUES (0, 'on', 'SW_CORE_01',  '192.168.120.2', 'switches', 1, 1, 7, 'both') ON DUPLICATE KEY UPDATE  `enabled`=VALUES(`enabled`), `hostname`=VALUES(`hostname`),  `ipaddress`=VALUES(`ipaddress`), `directory`=VALUES(`directory`),  `account`=VALUES(`account`), `devicetype`=VALUES(`devicetype`),  `schedule`=VALUES(`schedule`), `connect_type`=VALUES(`connect_type`)'
2018/02/20 14:12:22 - CMDPHP PHP ERROR NOTICE Backtrace:  (/plugins/routerconfigs/router-devices.php: 151  save_devices)(/plugins/routerconfigs/router-devices.php: 415  sql_save)(/lib/database.php: 978 CactiErrorHandler)(/lib/functions.php:  4408 cacti_debug_backtrace)
2018/02/20 14:12:22 - ERROR PHP NOTICE: Undefined index: connect_type in file: /opt/cacti/lib/database.php  on line: 978
2018/02/20 14:12:22 - CMDPHP PHP ERROR NOTICE Backtrace:  (/plugins/routerconfigs/router-devices.php: 151  save_devices)(/plugins/routerconfigs/router-devices.php: 415  sql_save)(/lib/database.php: 977 CactiErrorHandler)(/lib/functions.php:  4408 cacti_debug_backtrace)
2018/02/20 14:12:22 - ERROR PHP NOTICE: Undefined index: connect_type in file: /opt/cacti/lib/database.php  on line: 977
2018/02/20 14:12:22 - CMDPHP PHP ERROR NOTICE Backtrace:  (/plugins/routerconfigs/router-devices.php: 151  save_devices)(/plugins/routerconfigs/router-devices.php: 415  sql_save)(/lib/database.php: 976 CactiErrorHandler)(/lib/functions.php:  4408 cacti_debug_backtrace)
2018/02/20 14:12:22 - ERROR PHP NOTICE: Undefined index: connect_type in file: /opt/cacti/lib/database.php  on line: 976
2018/02/20 14:12:22 - CMDPHP PHP ERROR NOTICE Backtrace:  (/plugins/routerconfigs/router-devices.php: 151  save_devices)(/plugins/routerconfigs/router-devices.php: 415  sql_save)(/lib/database.php: 975 CactiErrorHandler)(/lib/functions.php:  4408 cacti_debug_backtrace)
2018/02/20 14:12:22 - ERROR PHP NOTICE: Undefined index: connect_type in file: /opt/cacti/lib/database.php  on line: 975

I'm not a software developer, only a network engineer, but if I can do anything to help tell me.

**Comment by netniV** [comment]
OK, you need to add the missing column.  There was an issue with the upgrade script, but there's still an issue with the new install part too.  The problem was that the code has never run the upgrade check! My latest patch makes that bit work, but the table creation code uses a newer array format, so I modified that but it appears to have not accepted the column when installing fresh.

See https://github.com/Cacti/plugin_routerconfigs/pull/28 which has the SQL to add the column.  I do apologise for that.

**Comment by rcsmota** [comment]
Hi @netniV  I have added the columm like a #28 and now I can create the host.

![screen shot 2018-02-20 at 13 27 42](https://user-images.githubusercontent.com/31240306/36426952-ab0aa7f0-1643-11e8-83ed-d694d6304dcf.png)

Now all working. But I notice 2 things.

1- At device configuration in Directory all ways show a error, but in the Cacti CLI it all fine.

![image](https://user-images.githubusercontent.com/31240306/36428159-176205a8-1647-11e8-95eb-d236e016f530.png)

![image](https://user-images.githubusercontent.com/31240306/36428124-fe87a15a-1646-11e8-8be7-7d171c30ba72.png)

![image](https://user-images.githubusercontent.com/31240306/36427956-8404b0c6-1646-11e8-978e-f44df743c11c.png)

2- Although everything is working i received the following messages on Cacti Log all time i make a backup


2018/02/20  15:00:54 - CMDPHP PHP ERROR WARNING Backtrace:  (/plugins/routerconfigs/router-download.php: 84  plugin_routerconfigs_download)(/plugins/routerconfigs/functions.php: 201  send_mail)(/lib/functions.php: 3467 mailer)(/lib/functions.php: 3601  setFrom)(/include/phpmailer/class.phpmailer.php: 1014  trim)(CactiErrorHandler)(/lib/functions.php: 4403 cacti_debug_backtrace)
2018/02/20 15:00:54 - ERROR PHP WARNING: trim() expects parameter 1  to be string, array given in file:  /opt/cacti/include/phpmailer/class.phpmailer.php  on line: 1014
2018/02/20 15:00:54 - CMDPHP PHP ERROR WARNING Backtrace:  (/plugins/routerconfigs/router-download.php: 84  plugin_routerconfigs_download)(/plugins/routerconfigs/functions.php: 201  send_mail)(/lib/functions.php: 3467 mailer)(/lib/functions.php: 3601  setFrom)(/include/phpmailer/class.phpmailer.php: 1013  trim)(CactiErrorHandler)(/lib/functions.php: 4403 cacti_debug_backtrace)
2018/02/20 15:00:54 - ERROR PHP WARNING: trim() expects parameter 1  to be string, array given in file:  /opt/cacti/include/phpmailer/class.phpmailer.php  on line: 1013
2018/02/20 15:00:54 - CMDPHP PHP ERROR NOTICE Backtrace:  (/plugins/routerconfigs/router-download.php: 84  plugin_routerconfigs_download)(/plugins/routerconfigs/functions.php: 201  send_mail)(/lib/functions.php: 3467 mailer)(/lib/functions.php: 3513  CactiErrorHandler)(/lib/functions.php: 4408 cacti_debug_backtrace)
2018/02/20 15:00:54 - ERROR PHP NOTICE: Array to string conversion in file: /opt/cacti/lib/functions.php  on line: 3513
2018/02/20 15:00:54 - CMDPHP PHP ERROR NOTICE Backtrace:  (/plugins/routerconfigs/router-download.php: 84  plugin_routerconfigs_download)(/plugins/routerconfigs/functions.php: 201  send_mail)(/lib/functions.php: 3467 mailer)(/lib/functions.php: 3513  CactiErrorHandler)(/lib/functions.php: 4408 cacti_debug_backtrace)
2018/02/20 15:00:54 - ERROR PHP NOTICE: Array to string conversion in file: /opt/cacti/lib/functions.php  on line: 3513
2018/02/20 15:00:54 - CMDPHP PHP ERROR NOTICE Backtrace:  (/plugins/routerconfigs/router-download.php: 84  plugin_routerconfigs_download)(/plugins/routerconfigs/functions.php: 201  send_mail)(/lib/functions.php: 3456  db_fetch_cell_prepared)(/lib/database.php: 261  execute)(CactiErrorHandler)(/lib/functions.php: 4408  cacti_debug_backtrace)
2018/02/20 15:00:54 - ERROR PHP NOTICE: Array to string conversion in file: /opt/cacti/lib/database.php  on line: 261

You not need apologise for nothing. It's a great work

Thanks!

**Comment by netniV** [comment]
Ah, you need an update from the cacti base. I should update the requires version of this plugin to 1.1.36 since it needs that change.  https://github.com/Cacti/cacti/pull/1371

**Comment by netniV** [comment]
Yes, the directories are using dirpath which just checks that a directory exists.  It has no concept of checking that it's relative or that it just needs to be valid directory characters.  Worse, you can't use filepath as a type for a file  you wish to create because it complains it doesn't exist.  There should be an option to say error unless it doesn't exist or just check for valid characters but that's probably one for @cigamit

**Comment by jpobeda** [comment]
I'm not sure if I should open a new one or not

I'm running 1.1.21 and getting those phpmailer errors so if it works, it's fine, no need to rush into it BUT
I noticed that it's sending the emails not honoring the settings

Root User <root@localhost.xx.yy.zz> | Root User <root@localhost.xx.yy.zz>

?

**Comment by seppeel** [comment]
thats right.

**Comment by netniV** [comment]
OK, so routerconfigs 1.3 was streamlined so that it wasn't duplicating lots of code etc.  One part of that was to make it utilise the underlying Cacti Base were possible, thus reducing a chunk of duplication plus incorporating the base functionality updates.  

However, as a result, there was an issue with the FROM as the base cacti function nicely ignores whether it's an array or not, but just tries to use it's own configuration settings as It thinks its not been set.  That fix went into the develop branch in the last couple of days.

**Comment by netniV** [comment]
I think this issue can now be closed, unless you believe there is something more outstanding?

**Comment by netniV** [comment]
@Fireball2k15 Do we need this open still?

**Comment by Fireball2k15** [comment]
Hi netniV,
no - I think it's done.
I will try your version with the next installation - I think this will be at the end of April.

Fireball
