### ISSUE TITLE
Create a "Tab" for routerconfigs

### ISSUE THREAD

**Issue by seppeel** [Cacti/plugin_routerconfigs#53]
We use the syslog plugin, too in cacti.
The syslog plugin has an own tab on top of the page (Console, Graphs, Reporting, Logs, Syslog).

Why don't create an own tab for routerconfigs? :-)

**Comment by netniV** [comment]
I thought about this, but I decided not to change it because unlike other tabs, RouterConfigs is not really an area that you'd expect most operators to go to constantly.  There may be a few senior admins who check out the backups etc, but on the whole, I would not expect an every day operator to be constantly looking at them especially given the backup email that gets generated.

**Comment by seppeel** [comment]
Thats OK for me.
For us, it would make sense, because its one of the few things we have to look at. Is it maybe possible to make this optional?
But then i would be much better to create an option for cacti (not routerconfigs) to choose the displayed tabs.

**Comment by Cramin** [comment]
Create new Tab in External Links an the bottom of console menu.

**Comment by netniV** [comment]
That's a good point @Cramin you can use your own External Links section to create the tab @seppeel

**Comment by seppeel** [comment]
Ooooh yes :-)
Closed.
