### ISSUE TITLE
Issue taking backup

### ISSUE THREAD

**Issue by andersonreloaded** [Cacti/plugin_routerconfigs#60]
Hi Folks,

Using Cacti version 1.1.36 on CentOS7 with PHP 5.4.16

Unable to take router configuration backup. The log file throws following messages.

`2018/04/03 15:57:29 - CMDPHP PHP ERROR Backtrace: (/plugins/routerconfigs/router-devices.php: 163 actions_devices)(/plugins/routerconfigs/router-devices.php: 334 plugin_routerconfigs_log)(/plugins/routerconfigs/functions.php: 910 CactiErrorHandler)(/lib/functions.php: 4579 cacti_debug_backtrace)`

`2018/04/03 15:57:29 - ERROR PHP RECOVERABLE_ERROR in Plugin 'routerconfigs': Argument 1 passed to plugin_routerconfigs_log() must be an instance of string, string given, called in /nms/cacti/plugins/routerconfigs/router-devices.php on line 334 and defined in file: /nms/cacti/plugins/routerconfigs/functions.php on line: 910 `

Any ideas to fix the issue ?

**Comment by netniV** [comment]
I presume this was a manual backup you were trying to take?

**Comment by netniV** [comment]
If you try the latest development version, this should work for you now.

**Comment by andersonreloaded** [comment]
Hi,
You are right, I was using the manual backup option.
Shall try and update. Thank you for responding!

**Comment by rtripon** [comment]
I had the same problem with php version 5.4. Had to install a box with php7 to get rid of it.

**Comment by netniV** [comment]
PHP 7 is better anyway :), 

From a personal view point, I wish the version support we did was 7.1 (as that has proper nullable typing in it!) but there are way too many still using the older PHP versions. 

Have you managed to re-try with PHP 5.4 @andersonreloaded ?

**Comment by andersonreloaded** [comment]
@netniV There are few observations on the plugin.

**1. Observation**
https://github.com/Cacti/plugin_routerconfigs/blob/5614bc2dee526655371507da2e5c0f6832cbbdb1/functions.php#L972

I suppose the code should be 
`$this->enablepw = $enablepw;` 
  
**2. Observation**
The backup directory field shown in the device add/edit field is relative to the parent directory under the settings section. The backup also is accordingly done. However since the field is of type directory and only the name is mentioned, it doesn't qualify as directory and 'x' mark is show against it.

**3. Observation**
The textarea dimensions are too small to view the configuration. May be a 'rconfig.css' should be defined to suit the visual needs to view the configurations. 

**4. Observation**
Is there a way to import devices from Cacti host table ? I have CDP discovery plugin, which saves the discovered Cisco/CDP enabled devices to Cacti host table. I feel a feature to import Cisco devices from Cacti host table to Routerconfig devices table will be very handy and saves lot of time by doing away with need to make manual entries.

Shall report any new observations if any.
Thank you!

**Comment by andersonreloaded** [comment]
I didn't see the earlier post :-(
The latest development version of the plugin works fine and the errors are not thrown in the logs!
Thank you for the quick fix.

**Comment by netniV** [comment]
So you've actually noticed a few of the things I have when I took on the plugin recently to get it working properly with the majority of devices now.  Thanks for posting your observations as they are always useful to double check what's in place.

1. The code is correct, the $pass comes via the constructor.  If you look back to way that constructor is initialized you will see that comes from the database.

2. It has always been that way. I am loath to change it's functionality because it would break existing systems.  However, it does not currently work properly with the standard Cacti text entry that expects it to be a proper directory.  So, this may change at some point i the future but not just yet.

3. If you can open an issue for that with a screenshot, I'll take a look.

4. Other plugins do have the facility to import from the main cacti database.  However, devices that are used to backup from may not always be the same as those you are monitoring.  THold, for example, uses only the main device database because you'd never have a threshold for something you were not monitoring.  MacTrack I think does a hybrid situation so may be something I'borrow' the code from.

Again, it would be best to open that as an issue to track it as a feature request.

For now, I'm going to close this issue as it's now resolved 👍

**Comment by andersonreloaded** [comment]
@netniV : Thank you for responding.
Regarding the first observation I shall revert the code and let you know, If I am right, with the current code the backup was not happening and "Error in Authentication" was reported in the debug log.

**Comment by andersonreloaded** [comment]
@netniV: With the original code, the back up is failing with "Error in authentication" reported in the Debug log. When I update the code with `$this->enablepw = $enablepw;` the back up is success. How the $pass and $enablepw take values from same variable. The constructor has two different arguments $pass (assume its the login password) and $enablepw (enable password). Correct me if I am wrong.

**Comment by netniV** [comment]
Ohhh... actually, you may be right. Let me review that again. Sorry, was in a meeting at the time so wasn't looking through it 100%

**Comment by netniV** [comment]
Do me a favour? As that is separate to the 5.4 issue, can you open that as a new issue for me to tag against?
