### ISSUE TITLE
Feature Request: Enable SCP method of backup

### ISSUE THREAD

**Issue by seppeel** [Cacti/plugin_routerconfigs#74]
Heyo, here i am again :)

my new company uses a different solution for config backups but this may change in the near future :) .
an important demand is, that the config transfer protocol **must** be encrypted. (connections via wan)

one solution could be to implement other file transfer protocols.

another idea would be not to transfer the config as file but save the text output of "show run". I dont know if its easy to do this, but it could make a lot of other things easier.
1. You can backup every device as long as you can customize the "show run" command and the config end (Related to #33 )
2. Everything will be encrypted as long as the device is able to accept ssh connections
3. The tftp-server will not be necessary to use routerconfigs

What do you think about that? @netniV 

Greetings

**Comment by netniV** [comment]
Personally, I would prefer to SCP the files from a device and I do this with my own custom backup scripts for my configuration differencing system.  Unfortunately, not all devices make their configuration available for download via SCP.  Cisco ASA firewalls for one but I'm open to discussions on this.

**Comment by netniV** [comment]
Oh, for those devices, I do use the show run with an expect script to capture the output into a file.

**Comment by seppeel** [comment]
thats interesting. we have a lot of ASA Firewalls here, too.

**Comment by andersonreloaded** [comment]
This is really interesting. We have a mix of Cisco 2950 and 2960 boxes. Looks like 2950 shall not get IOS upgrades but there's scope for 2960s with IOS 15.x release.

@netniV Any plans to provide SCP support in the plugin ?

**Comment by netniV** [comment]
We already have some a base class for issuing the commands of SSH/Telnet so I could potentially implement the show run option.  To keep things clean though, I've renamed this thread as an SCP one since that seems to be the prevalent request so can you create another for the ability to issue a "show run" style command to capture the configuration.

Implementing the SCP should be fairly easy using:
- [ssh2-connect](http://php.net/manual/en/function.ssh2-connect.php)
- then authenticating via
   - [password](http://php.net/manual/en/function.ssh2-auth-password.php)
   - [key](http://php.net/manual/en/function.ssh2-auth-pubkey-file.php)
- [ssh2-scp-recv](http://php.net/manual/en/function.ssh2-scp-recv.php)

**Comment by netniV** [comment]
Well, you would think it's as easy as that.  Except that even in my initial testing after several hours of work, I was receiving an error attempting to download from a Cisco 1941.  So, I tweaked, chopped, changed, and still got the same issue.  

Eventually, I think I tracked it down to PHP's inbuilt ssh2_scp_recv() function using options that it just doesn't support.  So, then I went to investigate if we could just use the PHPSecLib's implementation, but I've a feeling that relies on commands being available at the remote end (still going to try).

Finally, I have also considered allowing the use of the command line version of SCP but that would require using SSH keys rather than a username/password or else I'll have to start using proc_open to make it interactive - another complication).
